// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriageSystemAPI.Models;

namespace TriageSystem.Data.Migrations
{
    [DbContext(typeof(TriageSystemContext))]
    [Migration("20190205233748_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TriageSystemAPI.Models.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Date_of_birth");

                    b.Property<string>("Department");

                    b.Property<string>("Email");

                    b.Property<string>("Full_name");

                    b.Property<string>("Gender");

                    b.Property<int>("Hospital_id");

                    b.Property<string>("Position");

                    b.HasKey("StaffID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("TriageSystemAPI.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Admin");

                    b.Property<string>("Password");

                    b.Property<int>("StaffID");

                    b.Property<string>("UserType");

                    b.Property<string>("Username");

                    b.HasKey("UserID");

                    b.HasIndex("StaffID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TriageSystemAPI.Models.User", b =>
                {
                    b.HasOne("TriageSystemAPI.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
